In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv("A:\\dataset\\fakenews\\train.csv")

In [3]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
#Get the independent feature
X=messages.drop('label',axis=1)

In [5]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [6]:
#get dependent features
y=messages["label"]

In [7]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [8]:
messages.shape

(20800, 5)

In [9]:
messages.dropna()

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [10]:
import tensorflow as tf

In [11]:
tf.__version__

'2.1.0'

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [13]:
#Vocabulary size
voc_size=5000

In [14]:
messages['title'][6]

'Life: Life Of Luxury: Elton John’s 6 Favorite Shark Pictures To Stare At During Long, Transcontinental Flights'

In [15]:
import re

In [16]:
#preprocessing the data
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [17]:
ps=PorterStemmer()
corpus=[]

In [18]:
for i in range(0,len(messages)):
    review=re.sub('(^a-zA-z)','',str(messages['title'][i]))
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=''.join(review)
    corpus.append(review)

In [19]:
corpus

['housdemaide:didn’tevenseecomey’letterjasonchaffetztweet',
 'flynn:hillariclinton,bigwomancampu-breitbart',
 'truthmightgetfire',
 '15civiliankillsinglusairstrikidentifi',
 'iranianwomanjailfictionunpublishstoriwomanstonedeathadulteri',
 'jackimason:hollywoodwouldlovetrumpbombnorthkorealacktranbathroom(exclusvideo)-breitbart',
 'life:lifeluxury:eltonjohn’6favoritsharkpicturstarelong,transcontinentflight',
 'benoîthamonwinfrenchsocialistparty’presidentinomin-newyorktime',
 'excerptdraftscriptdonaldtrump’q&ampablackchurch’pastor-newyorktime',
 'back-channelplanukrainrussia,courtesitrumpassoci-newyorktime',
 'obama’organactionpartnersoros-link‘indivisible’disrupttrump’agenda',
 'bbccomedisketch"realhousewisis"causoutrag',
 'russianresearchdiscovsecretnazimilitaribase‘treasurhunter’arctic[photos]',
 'usofficiseelinktrumprussia',
 're:yes,paidgoverntrollsocialmedia,blogs,forumwebsit',
 'majorleagusoccer,argentinfindhomesuccess-newyorktime',
 'wellfargochiefabruptlistep-newyorktime',
 'anon

In [20]:
onehot_repr=[one_hot(words,voc_size) for words in corpus]

In [21]:
onehot_repr

[[3426, 2912],
 [4177, 4140, 824, 2817],
 [3077],
 [3386],
 [4655],
 [2831, 2312, 3420, 2817],
 [2688, 4664, 2991, 124],
 [3138, 3625],
 [3427, 2836, 3625],
 [4131, 1066, 3843, 3625],
 [3118, 3782],
 [2366, 2754, 3802],
 [4406, 278],
 [4050],
 [175, 1754, 2836, 1333, 825],
 [3381, 561, 3625],
 [2209, 3625],
 [3556, 2750, 776],
 [527],
 [202, 4595, 2817],
 [3312, 2742, 2395],
 [3786, 4712],
 [4566, 1243, 2817],
 [2087, 1331],
 [3834, 3625],
 [4226, 1482],
 [2446, 4159, 2817],
 [2737],
 [4927, 3625],
 [1573, 3625],
 [2767, 2888, 2817],
 [979,
  2960,
  3523,
  1065,
  1296,
  3384,
  2304,
  3594,
  4668,
  1850,
  3219,
  1254,
  537,
  2027,
  4090,
  460,
  3122,
  1881],
 [395, 2422, 3625],
 [1111, 4503, 3625],
 [4055, 3062, 3625],
 [3779, 3625],
 [175, 3811, 1730],
 [3623, 1980, 4090, 3577, 3384, 15],
 [545, 2817],
 [4871, 3625],
 [577, 101, 2817],
 [362],
 [2149, 3625],
 [8, 4072, 141],
 [1152, 2817],
 [1483, 3625],
 [3661, 4944, 776, 3723],
 [2228, 3859, 2783],
 [4338, 3343, 4456,

In [22]:
#embedding
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...    0 3426 2912]
 [   0    0    0 ... 4140  824 2817]
 [   0    0    0 ...    0    0 3077]
 ...
 [   0    0    0 ...    0 3114 3625]
 [   0    0    0 ...    0 1861 2365]
 [   0    0    0 ...    0  956 2319]]


In [23]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0, 3426, 2912])

In [24]:
#creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [25]:
len(embedded_docs),y.shape

(20800, (20800,))

In [26]:
import numpy as np

In [27]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [28]:
X_final.shape,y_final.shape

((20800, 20), (20800,))

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [30]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=75)

Train on 13936 samples, validate on 6864 samples
Epoch 1/10
13936/13936 [==============================] - 34s 2ms/sample - loss: 0.3866 - accuracy: 0.8515 - val_loss: 0.2486 - val_accuracy: 0.9104
Epoch 2/10
13936/13936 [==============================] - 30s 2ms/sample - loss: 0.1929 - accuracy: 0.9224 - val_loss: 0.2678 - val_accuracy: 0.8912
Epoch 3/10
13936/13936 [==============================] - 30s 2ms/sample - loss: 0.1414 - accuracy: 0.9417 - val_loss: 0.3230 - val_accuracy: 0.8807
Epoch 4/10
13936/13936 [==============================] - 30s 2ms/sample - loss: 0.1156 - accuracy: 0.9511 - val_loss: 0.3579 - val_accuracy: 0.8671
Epoch 5/10
13936/13936 [==============================] - 29s 2ms/sample - loss: 0.1009 - accuracy: 0.9550 - val_loss: 0.4209 - val_accuracy: 0.8645
Epoch 6/10
13936/13936 [==============================] - 31s 2ms/sample - loss: 0.0908 - accuracy: 0.9606 - val_loss: 0.4821 - val_accuracy: 0.8638
Epoch 7/10
13936/13936 [==============================] -

In [31]:
from tensorflow.keras.layers import Dropout

In [32]:
#creating model adding dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
#performance metrics and accuracy
y_pred=model.predict_classes(X_test)
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [34]:
print(confusion_matrix(y_pred,y_test))

[[ 771  888]
 [2678 2527]]


In [35]:
print(accuracy_score(y_pred,y_test))

0.4804778554778555


In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.46      0.22      0.30      3449
           1       0.49      0.74      0.59      3415

    accuracy                           0.48      6864
   macro avg       0.48      0.48      0.44      6864
weighted avg       0.48      0.48      0.44      6864

