In [61]:
import pandas as pd

In [62]:
messages=pd.read_csv("A:\\dataset\\fakenews\\train.csv")

In [63]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [64]:
#Get the independent feature
X=messages.drop('label',axis=1)

In [65]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [66]:
#get dependent features
y=messages["label"]

In [67]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [31]:
messages.shape

(20800, 5)

In [68]:
messages.dropna()

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [69]:
import tensorflow as tf

In [70]:
tf.__version__

'2.1.0'

In [71]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [72]:
#Vocabulary size
voc_size=5000

In [73]:
messages['title'][6]

'Life: Life Of Luxury: Elton John’s 6 Favorite Shark Pictures To Stare At During Long, Transcontinental Flights'

In [74]:
import re

In [75]:
#preprocessing the data
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [76]:
ps=PorterStemmer()
corpus=[]

In [77]:
for i in range(0,len(messages)):
    review=re.sub('(^a-zA-z)','',str(messages['title'][i]))
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=''.join(review)
    corpus.append(review)

In [78]:
corpus

['housdemaide:didn’tevenseecomey’letterjasonchaffetztweet',
 'flynn:hillariclinton,bigwomancampu-breitbart',
 'truthmightgetfire',
 '15civiliankillsinglusairstrikidentifi',
 'iranianwomanjailfictionunpublishstoriwomanstonedeathadulteri',
 'jackimason:hollywoodwouldlovetrumpbombnorthkorealacktranbathroom(exclusvideo)-breitbart',
 'life:lifeluxury:eltonjohn’6favoritsharkpicturstarelong,transcontinentflight',
 'benoîthamonwinfrenchsocialistparty’presidentinomin-newyorktime',
 'excerptdraftscriptdonaldtrump’q&ampablackchurch’pastor-newyorktime',
 'back-channelplanukrainrussia,courtesitrumpassoci-newyorktime',
 'obama’organactionpartnersoros-link‘indivisible’disrupttrump’agenda',
 'bbccomedisketch"realhousewisis"causoutrag',
 'russianresearchdiscovsecretnazimilitaribase‘treasurhunter’arctic[photos]',
 'usofficiseelinktrumprussia',
 're:yes,paidgoverntrollsocialmedia,blogs,forumwebsit',
 'majorleagusoccer,argentinfindhomesuccess-newyorktime',
 'wellfargochiefabruptlistep-newyorktime',
 'anon

In [79]:
onehot_repr=[one_hot(words,voc_size) for words in corpus]

In [80]:
onehot_repr

[[3907, 2669],
 [1947, 3938, 389, 1548],
 [3530],
 [2879],
 [3531],
 [1266, 3778, 4930, 1548],
 [900, 4297, 4730, 3760],
 [1068, 4017],
 [3681, 2678, 4017],
 [4939, 4903, 1297, 4017],
 [1063, 1373],
 [74, 299, 2228],
 [4100, 1223],
 [3828],
 [4939, 563, 77, 3844, 2021],
 [1709, 1740, 4017],
 [2884, 4017],
 [2431, 1076, 3891],
 [257],
 [4331, 4950, 1548],
 [3941, 1282, 2473],
 [2564, 1798],
 [2106, 3547, 1548],
 [2667, 2741],
 [4309, 4017],
 [2817, 4516],
 [3895, 3323, 1548],
 [4541],
 [3532, 4017],
 [723, 4017],
 [1494, 2209, 1548],
 [2676,
  4405,
  2332,
  1708,
  999,
  1688,
  4182,
  25,
  2200,
  749,
  2930,
  2122,
  368,
  2999,
  3607,
  3070,
  394,
  3868],
 [3366, 3392, 4017],
 [744, 2231, 4017],
 [2188, 1153, 4017],
 [1945, 4017],
 [4939, 1385, 3705],
 [4724, 792, 3607, 580, 1688, 3418],
 [2717, 1548],
 [4863, 4017],
 [2431, 2892, 1548],
 [127],
 [1465, 4017],
 [4439, 3044, 1469],
 [696, 1548],
 [699, 4017],
 [4221, 790, 1598, 479],
 [3519, 2069, 4895],
 [1104, 2980, 3171

In [81]:
#embedding
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...    0 3907 2669]
 [   0    0    0 ... 3938  389 1548]
 [   0    0    0 ...    0    0 3530]
 ...
 [   0    0    0 ...    0 2181 4017]
 [   0    0    0 ...    0 1806 2273]
 [   0    0    0 ...    0 2034 3147]]


In [82]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0, 3907, 2669])

In [85]:
#creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_5 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [86]:
len(embedded_docs),y.shape

(20800, (20800,))

In [87]:
import numpy as np

In [88]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [93]:
X_final.shape,y_final.shape

((20800, 20), (20800,))

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [95]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=75)

Train on 13936 samples, validate on 6864 samples
Epoch 1/10
13936/13936 [==============================] - 41s 3ms/sample - loss: 0.3985 - accuracy: 0.8383 - val_loss: 0.2450 - val_accuracy: 0.9104
Epoch 2/10
13936/13936 [==============================] - 30s 2ms/sample - loss: 0.1942 - accuracy: 0.9219 - val_loss: 0.2690 - val_accuracy: 0.8970
Epoch 3/10
13936/13936 [==============================] - 32s 2ms/sample - loss: 0.1449 - accuracy: 0.9397 - val_loss: 0.3276 - val_accuracy: 0.8807
Epoch 4/10
13936/13936 [==============================] - 31s 2ms/sample - loss: 0.1181 - accuracy: 0.9512 - val_loss: 0.3727 - val_accuracy: 0.8737
Epoch 5/10
13936/13936 [==============================] - 33s 2ms/sample - loss: 0.1018 - accuracy: 0.9569 - val_loss: 0.3851 - val_accuracy: 0.8647
Epoch 6/10
13936/13936 [==============================] - 32s 2ms/sample - loss: 0.0924 - accuracy: 0.9600 - val_loss: 0.4216 - val_accuracy: 0.8749
Epoch 7/10
13936/13936 [==============================] -

In [96]:
from tensorflow.keras.layers import Dropout

In [97]:
#creating model adding dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [98]:
#performance metrics and accuracy
y_pred=model.predict_classes(X_test)
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [100]:
print(confusion_matrix(y_pred,y_test))

[[   6    7]
 [3443 3408]]


In [101]:
print(accuracy_score(y_pred,y_test))

0.4973776223776224
