In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv("A:\\dataset\\fakenews\\train.csv")

In [3]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
#Get the independent feature
X=messages.drop('label',axis=1)

In [5]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [6]:
#get dependent features
y=messages["label"]

In [7]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [8]:
messages.shape

(20800, 5)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [10]:
messages.dropna()

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [11]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [12]:
messages.reset_index(inplace=True)

In [13]:
messages.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

In [14]:
messages.shape

(20800, 6)

In [15]:
messages.dropna()

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
20795  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 6 columns]

In [16]:
messages['text'][6]

'Ever wonder how Britain’s most iconic pop pianist gets through a long flight? Here are the six pictures of sharks Sir Elton John likes to stare at to pass the time on an airplane. 1. A Shark Swimming \nSit next to Elton John on a flight and you’ll see a man living in the lap of luxury, as he immediately tapes this photo of a shark darting through the ocean over his window to stare at throughout the trip. The platinum-selling artist has been known to pull his window shade down to make the shark disappear, and then quickly retract it to mark the animal’s triumphant return. He will often repeat this act dozens of times per flight. 2. A Great White Shark Leaping Into The Air \nWhen you’re an international pop sensation worth an estimated $450 million, people go the extra mile to make you happy. Flight crews are instructed to place this photo of a breaching great white in Elton John’s seat-back pocket before he even boards the plane. The five-time Grammy winner loves to pull the image out 

In [17]:
import re

In [18]:
#preprocessing the data
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [19]:
ps=PorterStemmer()
corpus=[]

In [20]:
for i in range(0,len(messages)):
    review=re.sub('(^a-zA-z)','',str(messages['title'][i]))
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=''.join(review)
    corpus.append(review)

In [22]:
corpus[3]

'15civiliankillsinglusairstrikidentifi'

In [23]:
#Applying countVectorizer
#Creating bag of words model
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X=cv.fit_transform(corpus).toarray()

In [24]:
X.shape

(20800, 5000)

In [25]:
X.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [26]:
y=messages['label']

In [27]:
#Divide the dataset
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train ,y_test=train_test_split(X,y,test_size=0.4,random_state=0)

In [28]:
cv.get_feature_names()[:20]

['000',
 '000annual',
 '000annual breitbart',
 '000bornilleg1year',
 '000childreneveriyear',
 '000email',
 '000email691',
 '000email691 000second',
 '000emailmight',
 '000emailmight missing',
 '000employe',
 '000foreignwiretransfercaughttape',
 '000home',
 '000jobs',
 '000mailerfalsconnectlavegacopkiller',
 '000monthfoundatrunbankertiefinancicrisi',
 '000second',
 '000u',
 '000u treasuri',
 '000victim']

In [29]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

In [30]:
count_df=pd.DataFrame(X_train,columns=cv.get_feature_names())

In [31]:
count_df.head()

000  000annual  000annual breitbart  000bornilleg1year  \
0  0.0        0.0                  0.0                0.0   
1  0.0        0.0                  0.0                0.0   
2  0.0        0.0                  0.0                0.0   
3  0.0        0.0                  0.0                0.0   
4  0.0        0.0                  0.0                0.0   

   000childreneveriyear  000email  000email691  000email691 000second  \
0                   0.0       0.0          0.0                    0.0   
1                   0.0       0.0          0.0                    0.0   
2                   0.0       0.0          0.0                    0.0   
3                   0.0       0.0          0.0                    0.0   
4                   0.0       0.0          0.0                    0.0   

   000emailmight  000emailmight missing  ...  zuhdijasser  американо  \
0            0.0                    0.0  ...          0.0        0.0   
1            0.0                    0.0  ...          0.0        0.0   
2            0.0                    0.0  ...          0.0        0.0   
3            0.0                    0.0  ...          0.0        0.0   
4            0.0                    0.0  ...          0.0        0.0   

   будущеевнутреннейполитикирк  керри  компанияalibabaоткрылавакансиюкота  \
0                          0.0    0.0                                 0.0   
1                          0.0    0.0                                 0.0   
2                          0.0    0.0                                 0.0   
3                          0.0    0.0                                 0.0   
4                          0.0    0.0                                 0.0   

   новоевосточноеобозрение  путин  сша  тьерримейсан  чуркин  
0                      0.0    0.0  0.0           0.0     0.0  
1                      0.0    0.0  0.0           0.0     0.0  
2                      0.0    0.0  0.0           0.0     0.0  
3                      0.0    0.0  0.0           0.0     0.0  
4                      0.0    0.0  0.0           0.0     0.0  

[5 rows x 5000 columns]

In [32]:
#MultinomialNB algorithm
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [33]:
from sklearn import metrics
import numpy as np
import itertools

In [34]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
score=metrics.accuracy_score(y_test,pred)
print("accuracy: %.3f" % score)

accuracy: 0.715


In [35]:
cm=metrics.confusion_matrix(y_test,pred)

In [36]:
print(cm)

[[3976  127]
 [2247 1970]]


In [37]:
y_train.shape

(12480,)

In [38]:
#PASSIVE AGGRESSIVE CLASSIFIER ALGORITHM it is best algorithm for text data
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf=PassiveAggressiveClassifier()

In [39]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
score=metrics.accuracy_score(y_test,pred)
print("accuracy: %.3f" % score)
cm=metrics.confusion_matrix(y_test,pred)
print(cm)

accuracy: 0.715
[[3976  127]
 [2247 1970]]


In [40]:
#multinomial classifier with hyperparameter
classifier=MultinomialNB(alpha= 1.0e-10)

In [41]:
previous_score=0
for alpha in np.arange(0,1,0.1):
    sub_classifier=MultinomialNB(alpha=alpha)
    sub_classifier.fit(X_train,y_train)
    y_pred=sub_classifier.predict(X_test)
    score=metrics.accuracy_score(y_test,y_pred)
    if score>previous_score:
        classifier=sub_classifier
        print("Alpha: {}, Score : {}".format(alpha,score))

C:\Users\karthick\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


Alpha: 0.0, Score : 0.7001201923076923
Alpha: 0.1, Score : 0.7036057692307692
Alpha: 0.2, Score : 0.7057692307692308
Alpha: 0.30000000000000004, Score : 0.7099759615384615
Alpha: 0.4, Score : 0.7118990384615385
Alpha: 0.5, Score : 0.7132211538461538
Alpha: 0.6000000000000001, Score : 0.7141826923076923
Alpha: 0.7000000000000001, Score : 0.7147836538461538
Alpha: 0.8, Score : 0.7143028846153846
Alpha: 0.9, Score : 0.7145432692307693


In [42]:
#get features names
features_names=cv.get_feature_names()

In [43]:
classifier.coef_[0]

array([-7.80545284, -9.22972757, -9.22972757, ..., -8.24425813,
       -8.64993152, -9.22972757])

In [44]:
#most real 
sorted(zip(classifier.coef_[0], features_names),reverse=True)[:20]

[(-3.322550840437879, 'nan'),
 (-4.449266922020272, 'video'),
 (-5.069779380015914, 're'),
 (-5.137285773074856, 'breaking'),
 (-5.301288220638073, 'trump'),
 (-5.637406313140133, 'america'),
 (-5.643377551637662, 'it'),
 (-5.698011383107822, 'russianews'),
 (-5.7440879752884895, 'truthfe'),
 (-5.837369536369076, 'here'),
 (-5.89308063514239, 'hillary'),
 (-5.915366654890654, '2016'),
 (-5.925118728597857, 'russia'),
 (-5.945153269797702, 'watch'),
 (-5.959581590090346, 'новоевосточноеобозрение'),
 (-5.976201211425938, 'legorafi'),
 (-6.013963805988666, 'neweasternoutlook'),
 (-6.089666646379119, 'obama'),
 (-6.0966215659811525, 'wikileaks'),
 (-6.107845575302861, 'onion america finestnewssourc')]

In [45]:
#most fake
sorted(zip(classifier.coef_[0], features_names))[:5000]

[(-9.229727571023272, '000annual'),
 (-9.229727571023272, '000annual breitbart'),
 (-9.229727571023272, '000victim'),
 (-9.229727571023272, '100'),
 (-9.229727571023272, '11 11'),
 (-9.229727571023272, '11bill'),
 (-9.229727571023272, '125'),
 (-9.229727571023272, '16dr'),
 (-9.229727571023272, '170'),
 (-9.229727571023272, '17greatstorinothpolit'),
 (-9.229727571023272, '17greatstorinothpolit newyorktime'),
 (-9.229727571023272, '1984'),
 (-9.229727571023272, '1a'),
 (-9.229727571023272, '1billion'),
 (-9.229727571023272, '20 photorevealeffectgivealcohol'),
 (-9.229727571023272, '200'),
 (-9.229727571023272, '2016 breitbart'),
 (-9.229727571023272, '2016 russianstrikedestroy300terrorists'),
 (-9.229727571023272, '2016 russianstrikedestroy300terrorists oilfacil'),
 (-9.229727571023272, '20wine'),
 (-9.229727571023272, '20wine 20'),
 (-9.229727571023272, '211'),
 (-9.229727571023272, '27 16'),
 (-9.229727571023272, '3charlottareacountireportvotemachinpickwrongcandid'),
 (-9.229727571023