In [74]:
import pandas as pd

In [75]:
messages=pd.read_csv("A:\\dataset\\fakenews\\train.csv")

In [77]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [78]:
#Get the independent feature
X=messages.drop('label',axis=1)

In [79]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [80]:
#get dependent features
y=messages["label"]

In [81]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [82]:
messages.shape

(20800, 5)

In [83]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [84]:
messages.dropna()

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [85]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [86]:
messages.reset_index(inplace=True)

In [87]:
messages.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

In [90]:
messages.shape

(20800, 6)

In [89]:
messages.dropna()

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
20795  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 6 columns]

In [91]:
messages['title'][6]

'Life: Life Of Luxury: Elton John’s 6 Favorite Shark Pictures To Stare At During Long, Transcontinental Flights'

In [92]:
import re

In [93]:
#preprocessing the data
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [94]:
ps=PorterStemmer()
corpus=[]

In [95]:
for i in range(0,len(messages)):
    review=re.sub('(^a-zA-z)','',str(messages['title'][i]))
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=''.join(review)
    corpus.append(review)

In [96]:
corpus[3]

'15civiliankillsinglusairstrikidentifi'

In [97]:
#Applying countVectorizer
#Creating bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,ngram_range=(1,3))
X=cv.fit_transform(corpus).toarray()

In [98]:
X.shape

(20800, 5000)

In [99]:
X.reshape(-1,1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [100]:
y=messages['label']

In [101]:
#Divide the dataset
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train ,y_test=train_test_split(X,y,test_size=0.4,random_state=0)

In [102]:
cv.get_feature_names()[:20]

['000',
 '000annual',
 '000annual breitbart',
 '000bornilleg1year',
 '000childreneveriyear',
 '000email',
 '000email691',
 '000email691 000second',
 '000emailmight',
 '000emailmight missing',
 '000employe',
 '000foreignwiretransfercaughttape',
 '000home',
 '000jobs',
 '000mailerfalsconnectlavegacopkiller',
 '000monthfoundatrunbankertiefinancicrisi',
 '000second',
 '000u',
 '000u treasuri',
 '000victim']

In [103]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [104]:
count_df=pd.DataFrame(X_train,columns=cv.get_feature_names())

In [105]:
count_df.head()

000  000annual  000annual breitbart  000bornilleg1year  \
0    0          0                    0                  0   
1    0          0                    0                  0   
2    0          0                    0                  0   
3    0          0                    0                  0   
4    0          0                    0                  0   

   000childreneveriyear  000email  000email691  000email691 000second  \
0                     0         0            0                      0   
1                     0         0            0                      0   
2                     0         0            0                      0   
3                     0         0            0                      0   
4                     0         0            0                      0   

   000emailmight  000emailmight missing  ...  zuhdijasser  американо  \
0              0                      0  ...            0          0   
1              0                      0  ...            0          0   
2              0                      0  ...            0          0   
3              0                      0  ...            0          0   
4              0                      0  ...            0          0   

   будущеевнутреннейполитикирк  керри  компанияalibabaоткрылавакансиюкота  \
0                            0      0                                   0   
1                            0      0                                   0   
2                            0      0                                   0   
3                            0      0                                   0   
4                            0      0                                   0   

   новоевосточноеобозрение  путин  сша  тьерримейсан  чуркин  
0                        0      0    0             0       0  
1                        0      0    0             0       0  
2                        0      0    0             0       0  
3                        0      0    0             0       0  
4                        0      0    0             0       0  

[5 rows x 5000 columns]

In [106]:
#MultinomialNB algorithm
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [107]:
from sklearn import metrics
import numpy as np
import itertools

In [108]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
score=metrics.accuracy_score(y_test,pred)
print("accuracy: %.3f" % score)

accuracy: 0.713


In [113]:
cm=metrics.confusion_matrix(y_test,pred)

In [114]:
print(cm)

[[3992  111]
 [2273 1944]]


In [119]:
y_train.shape

(12480,)

In [126]:
#PASSIVE AGGRESSIVE CLASSIFIER ALGORITHM it is best algorithm for text data
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf=PassiveAggressiveClassifier()

In [128]:
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
score=metrics.accuracy_score(y_test,pred)
print("accuracy: %.3f" % score)
cm=metrics.confusion_matrix(y_test,pred)
print(cm)

accuracy: 0.713
[[3992  111]
 [2273 1944]]


In [131]:
#multinomial classifier with hyperparameter
classifier=MultinomialNB(alpha=0.1)

In [134]:
previous_score=0
for alpha in np.arange(0,1,0.1):
    sub_classifier=MultinomialNB(alpha=alpha)
    sub_classifier.fit(X_train,y_train)
    y_pred=sub_classifier.predict(X_test)
    score=metrics.accuracy_score(y_test,y_pred)
    if score>previous_score:
        classifier=sub_classifier
        print("Alpha: {}, Score : {}".format(alpha,score))

C:\Users\karthick\Anaconda3\envs\tf-gpu\lib\site-packages\sklearn\naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


Alpha: 0.0, Score : 0.7014423076923076
Alpha: 0.1, Score : 0.713701923076923
Alpha: 0.2, Score : 0.7145432692307693
Alpha: 0.30000000000000004, Score : 0.7149038461538462
Alpha: 0.4, Score : 0.7144230769230769
Alpha: 0.5, Score : 0.7144230769230769
Alpha: 0.6000000000000001, Score : 0.7144230769230769
Alpha: 0.7000000000000001, Score : 0.7139423076923077
Alpha: 0.8, Score : 0.7139423076923077
Alpha: 0.9, Score : 0.7134615384615385


In [135]:
#get features names
features_names=cv.get_feature_names()

In [136]:
classifier.coef_[0]

array([-7.62203355, -9.50234642, -9.50234642, ..., -8.33227516,
       -8.75513201, -9.50234642])

In [138]:
#most real 
sorted(zip(classifier.coef_[0], features_names),reverse=True)[:20]

[(-3.5951696853226256, 'nan'),
 (-4.335023978988596, 'video'),
 (-5.003772076185745, 're'),
 (-5.028804672398363, 'trump'),
 (-5.054480023738593, 'america'),
 (-5.121709635523191, 'breaking'),
 (-5.447667110078349, '2016'),
 (-5.486964897492719, 'onion america finestnewssourc'),
 (-5.486964897492719, 'onion america'),
 (-5.486964897492719, 'onion'),
 (-5.486964897492719, 'finestnewssourc'),
 (-5.486964897492719, 'america finestnewssourc'),
 (-5.527870395833322, 'it'),
 (-5.638114074316221, 'hillary'),
 (-5.6617000733221, 'truthfe'),
 (-5.816248604755959, 'russianews'),
 (-5.84449907104181, 'here'),
 (-5.84449907104181, 'clinton'),
 (-5.873570885863787, 'russia'),
 (-5.934379890459393, 'watch')]

In [139]:
#most fake
sorted(zip(classifier.coef_[0], features_names))[:5000]

[(-9.502346415908018, '000annual'),
 (-9.502346415908018, '000annual breitbart'),
 (-9.502346415908018, '000victim'),
 (-9.502346415908018, '100'),
 (-9.502346415908018, '11 11'),
 (-9.502346415908018, '11bill'),
 (-9.502346415908018, '125'),
 (-9.502346415908018, '16dr'),
 (-9.502346415908018, '170'),
 (-9.502346415908018, '17greatstorinothpolit'),
 (-9.502346415908018, '17greatstorinothpolit newyorktime'),
 (-9.502346415908018, '1984'),
 (-9.502346415908018, '1a'),
 (-9.502346415908018, '1billion'),
 (-9.502346415908018, '20 photorevealeffectgivealcohol'),
 (-9.502346415908018, '200'),
 (-9.502346415908018, '2016 breitbart'),
 (-9.502346415908018, '2016 russianstrikedestroy300terrorists'),
 (-9.502346415908018, '2016 russianstrikedestroy300terrorists oilfacil'),
 (-9.502346415908018, '20wine'),
 (-9.502346415908018, '20wine 20'),
 (-9.502346415908018, '211'),
 (-9.502346415908018, '27 16'),
 (-9.502346415908018, '3charlottareacountireportvotemachinpickwrongcandid'),
 (-9.502346415908