In [1]:
import pandas as pd

In [2]:
import nltk

In [5]:
messages=pd.read_csv("A:\\dataset\\smsspamcollection\\SMSSpamCollection",sep='\t',names=["lable","message"])

In [6]:
messages.head()

lable                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
messages.shape

(5572, 2)

In [9]:
#cleaning the texts
import re #regular expression
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [10]:
ps=PorterStemmer()

In [11]:
wordnet=WordNetLemmatizer()

In [15]:
corpus=[]

In [17]:
for i in range(len(messages)):
    review=re.sub('(^a-zA-z)','',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=''.join(review)
    corpus.append(review)

In [18]:
corpus

['gojurongpoint,crazy..availablebugisngreatworldlaebuffet...cinegotamorewat...',
 'oklar...jokingwifuoni...',
 "freeentry2wklycompwinfacupfinaltkts21stmay2005.textfa87121receiveentryquestion(stdtxtrate)t&c'sapply08452810075over18's",
 'udunsayearlyhor...ucalreadysay...',
 'nahthinkgousf,lifearoundthough',
 "freemsgheydarling3week'swordback!i'dlikefunstill?tbok!xxxstdchgssend,£1.50rcv",
 'evenbrotherlikespeakme.treatlikeaidpatent.',
 "perrequest'mellemelle(oruminnaminungintenurunguvettam)'setcallertunecallers.press*9copyfriendcallertune",
 'winner!!valuednetworkcustomerselectedreceivea£900prizereward!claimcall09061701461.claimcodekl341.valid12houronly.',
 'mobile11monthmore?urentitledupdatelatestcolourmobilecamerafree!callmobileupdatecofree08002986030',
 "i'mgonnahomesoonwanttalkstuffanymoretonight,k?i'vecriedenoughtoday.",
 'sixchancewincash!10020,000poundtxt>csh11send87575.cost150p/day,6days,16+tsandcsapplyreplyhl4info',
 'urgent!1weekfreemembership£100,000prizejackpot!txtword:claimno

In [19]:
# creating the TFIDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [20]:
x=tf.fit_transform(corpus).toarray()

In [21]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
y=pd.get_dummies(messages['lable'])

In [24]:
y=y.iloc[:,1].values

In [25]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [27]:
#train test split
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [31]:
#training model using naive bayes classifier
from sklearn.naive_bayes import MultinomialNB

In [32]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [33]:
y_pred=spam_detect_model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)

In [36]:
confusion_m

array([[955,   0],
       [ 98,  62]], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [39]:
accuracy

0.9121076233183857